### ISSUE TITLE
Support of goimports?

### ISSUE THREAD

**Issue by artem-sidorenko** [jbrudvik/nova-go-formatter#1]
Many thanks for a great extension! Any chance to see goimports (or similar) support to manage the imports automatically?

**Comment by jbrudvik** [comment]
@artem-sidorenko Hey, good idea. I'll see what I can do.

**Comment by jbrudvik** [comment]
@artem-sidorenko Thanks again for your suggestion. I've implemented it (d0a4da0) and released it in [version 0.0.5](https://extensions.panic.com/extensions/me.brudvik/me.brudvik.nova-go-formatter/).

Here's what I've changed:

- Add goimports support and make it the new default formatter.
- Add an extension preference "Use goimports if available" to control use of goimports vs gofmt.

Please check it out and let me know what you think!
